### ISSUE TITLE
Popup overlaps pum window when enabling border option on pum.vim

### ISSUE THREAD

**Issue by uplus** [matsui54/denops-popup-preview.vim#16]
### Problem

Popup overlaps pum window when enabling border option on pum.vim.

![Screenshot_20220614_062741](https://user-images.githubusercontent.com/10358398/173451639-aa86a476-3484-443f-b898-07b8892fe066.jpg)

### Options

Enable pum.vim border.

```vim
call pum#set_option({ 'border': 'single' })
```

### Environments

- neovim: https://github.com/neovim/neovim/tree/2b252430aa9ef52de7da733e2c0221c97111bce2
- ddc.vim: https://github.com/Shougo/ddc.vim/tree/4be33d4e5d0c62da05b8f28c34c5ebc2d40b0d62
- pum.vim: https://github.com/Shougo/pum.vim/tree/9c94a23eb575fd880eedd428711799377789eb6c
- denops-popup-preview.vim: https://github.com/matsui54/denops-popup-preview.vim/tree/46e8f044b4bf4cfb255a7adb1fda4dd708a7b02f

Thanks for great plugin!

**Comment by matsui54** [comment]
Thanks for reporting! Please wait until the fix in pum.vim is merged.

**Comment by matsui54** [comment]
It's merged. Please update pum.vim.

**Comment by uplus** [comment]
Thank you for the quick fix!
I have confirmed that the problem has been resolved in my environment.
